modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${ae_addon_mod_id}"
version="${mod_version}"
displayName="${ae_addon_mod_name}"
authors="${mod_authors}"
description='''Adds full-grid virtual tick acceleration for JDT Extras and AE2.'''

[[mixins]]
config="mixins.jdte_ae.json"

[[dependencies.${ae_addon_mod_id}]]
modId="jdte"
type="required"
versionRange="[${mod_version}]"
ordering="AFTER"
side="BOTH"

[[dependencies.${ae_addon_mod_id}]]
modId="ae2"
type="required"
versionRange="[19.2.17,20)"
ordering="AFTER"
side="BOTH"

[[dependencies.${ae_addon_mod_id}]]
modId="minecraft"
type="required"
versionRange="${ae_addon_minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${ae_addon_mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
